### ISSUE TITLE
does not support LaTex math while asciidoctor installed by ruby do

### ISSUE THREAD

**Issue by travisbikkle** [hcoona/hexo-renderer-asciidoc#11]
LaTex math not support while asciidoctor installed by ruby do.
Do you have a dev doc? How can i update this asciidoctor.js ?

**Comment by travisbikkle** [comment]
Hi, I checked [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js/issues/524) and found the solution.
In order to render fontawesome and stem content properly, we need 2 modification here:

1. asciidoctor.convert() must be given arguments like this: 
```javascript
asciidoctor.convert(data, {header_footer: true}) 
```
2. mathjax must be included like below to render latex content
```html
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js' async></script>
```
Since I'm not familiar with hexo dev and npm package publishment, could you pls find a way to fix this?

**Comment by hcoona** [comment]
This is a kind of Hexo issue. The converter just convert asciidoc to html.
