### ISSUE TITLE
Support for text formatting

### ISSUE THREAD

**Issue by kbyyd24** [hcoona/hexo-renderer-asciidoc#18]
I have tried to set my text color following but doesn't work.
From [here](https://www.methods.co.nz/asciidoc/chunked/ch10.html) at 10.1.1 , I have tried this but it doesn't work:

```
本文是个人的读书总结，不是系统的知识梳理， [big red]#慎读#。
```

the format is :

![image](https://user-images.githubusercontent.com/9191275/73548859-74892580-447c-11ea-9fdd-4dffe303d9ae.png)

The two words `慎读` are not `big and red`, they are normal.

this happend at version 1.2.2.

**Comment by hcoona** [comment]
Please check the generated HTML. It should assign a CSS class on it (with HTML span tag). You need to edit your CSS for showing it with desired style.
