### ISSUE TITLE
{} replacement sabotages use of passthrough with JS/CSS

### ISSUE THREAD

**Issue by aidanhs** [hcoona/hexo-renderer-asciidoc#2]
```
  return $.html()
             .replace(/{/g, '&#123;')
             .replace(/}/g, '&#125;');
```

If you're using asciidoc passthrough functionality (`+++`), '{' and '}' still gets replaced, making both JS and CSS broken.

Why do these two lines exist? It was added in https://github.com/hcoona/hexo-renderer-asciidoc/commit/7f3559ed3fbcab047655871c70ca2a2ff7a78011 with no explanation why.

**Comment by aidanhs** [comment]
Maybe related to https://github.com/hexojs/hexo/commit/683fd0a19c4f94216dcc13c35970135d7a6ef03e?

But the markdown plugin doesn't do it - https://github.com/hexojs/hexo-renderer-marked/blob/master/index.js

**Comment by hcoona** [comment]
I forgot why. I think it is related to the rendering of code blocks.

The asciidoctor engine is different from markdown engine.

**Comment by hcoona** [comment]
I'm currently in some troubles and have no time to test & fix it.

**Comment by aidanhs** [comment]
I've figured away around this. If you do escape both asciidoc (`++++`) and hexo (`{% raw %}`):

```
Some asciidoc text

++++
{% raw %}
<script>(function () {alert(1);})()</script>
{% endraw %}
++++

Some more asciidoc text
```

It will work. I'll close this issue as it's not a problem.

Thanks for your time and the plugin, hope your troubles get better :)
