### ISSUE TITLE
Configure highlight

### ISSUE THREAD

**Issue by niahoo** [hcoona/hexo-renderer-asciidoc#6]
Hello !

Thanks for this plugin, it's very helpful !

But it seems to ignore the configuration options of highlight. Plus some names are wronk : `hexo-util` uses `autoDetect` and `tab` instead of `auto_detect` and `tab_replace`. (`tab` accepts the replacement string).

`line_number` seems to have no effect.

Do you still maintain this package ?

Thank you !

**Comment by hcoona** [comment]
All about the dependencies upgrading. I made some fixes & fixed the depedency versions now. It should now works with Hexo 3.2.2 & Node 6.10.0 on Linux. I'm not sure why Windows still failed.

Thank you for reporting. I'm not active maintaining this plugin. PR is welcomed.
