### ISSUE TITLE
unsupported :toc:

### ISSUE THREAD

**Issue by wicksome** [hcoona/hexo-renderer-asciidoc#8]
I used asciidoc content(https://asciidoctor.org/docs/asciidoc-article/)
but occured in `:toc:`

Error Message
![image](https://user-images.githubusercontent.com/5036939/43245930-08b32518-90eb-11e8-980b-cc1def579552.png)

**Comment by hcoona** [comment]
The dependency `asciidoctor.js` updated. Upgrade to v2.1.1 to use `:toc:` feature.
